# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_client.models.entity_ref import EntityRef
from openziti_edge_client.models.link import Link
from openziti_edge_client.models.tags import Tags
from typing import Optional, Set
from typing_extensions import Self

class AuthenticatorDetail(BaseModel):
    """
    A singular authenticator resource
    """ # noqa: E501
    links: Dict[str, Link] = Field(description="A map of named links", alias="_links")
    created_at: datetime = Field(alias="createdAt")
    id: StrictStr
    tags: Optional[Tags] = None
    updated_at: datetime = Field(alias="updatedAt")
    cert_pem: Optional[StrictStr] = Field(default=None, alias="certPem")
    extend_requested_at: Optional[datetime] = Field(default=None, alias="extendRequestedAt")
    fingerprint: Optional[StrictStr] = None
    identity: EntityRef
    identity_id: StrictStr = Field(alias="identityId")
    is_extend_requested: Optional[StrictBool] = Field(default=None, alias="isExtendRequested")
    is_issued_by_network: Optional[StrictBool] = Field(default=None, alias="isIssuedByNetwork")
    is_key_roll_requested: Optional[StrictBool] = Field(default=None, alias="isKeyRollRequested")
    last_auth_resolved_to_root: Optional[StrictBool] = Field(default=None, alias="lastAuthResolvedToRoot")
    last_extend_rolled_keys: Optional[StrictBool] = Field(default=None, alias="lastExtendRolledKeys")
    method: StrictStr
    username: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["_links", "createdAt", "id", "tags", "updatedAt", "certPem", "extendRequestedAt", "fingerprint", "identity", "identityId", "isExtendRequested", "isIssuedByNetwork", "isKeyRollRequested", "lastAuthResolvedToRoot", "lastExtendRolledKeys", "method", "username"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthenticatorDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in links (dict)
        _field_dict = {}
        if self.links:
            for _key_links in self.links:
                if self.links[_key_links]:
                    _field_dict[_key_links] = self.links[_key_links].to_dict()
            _dict['_links'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        # override the default output from pydantic by calling `to_dict()` of identity
        if self.identity:
            _dict['identity'] = self.identity.to_dict()
        # set to None if extend_requested_at (nullable) is None
        # and model_fields_set contains the field
        if self.extend_requested_at is None and "extend_requested_at" in self.model_fields_set:
            _dict['extendRequestedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthenticatorDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_links": dict(
                (_k, Link.from_dict(_v))
                for _k, _v in obj["_links"].items()
            )
            if obj.get("_links") is not None
            else None,
            "createdAt": obj.get("createdAt"),
            "id": obj.get("id"),
            "tags": Tags.from_dict(obj["tags"]) if obj.get("tags") is not None else None,
            "updatedAt": obj.get("updatedAt"),
            "certPem": obj.get("certPem"),
            "extendRequestedAt": obj.get("extendRequestedAt"),
            "fingerprint": obj.get("fingerprint"),
            "identity": EntityRef.from_dict(obj["identity"]) if obj.get("identity") is not None else None,
            "identityId": obj.get("identityId"),
            "isExtendRequested": obj.get("isExtendRequested"),
            "isIssuedByNetwork": obj.get("isIssuedByNetwork"),
            "isKeyRollRequested": obj.get("isKeyRollRequested"),
            "lastAuthResolvedToRoot": obj.get("lastAuthResolvedToRoot"),
            "lastExtendRolledKeys": obj.get("lastExtendRolledKeys"),
            "method": obj.get("method"),
            "username": obj.get("username")
        })
        return _obj


