# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Capabilities(str, Enum):
    """
    Capabilities
    """

    """
    allowed enum values
    """
    OIDC_AUTH = 'OIDC_AUTH'
    HA_CONTROLLER = 'HA_CONTROLLER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Capabilities from a JSON string"""
        return cls(json.loads(json_str))


