# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_client.models.entity_ref import EntityRef
from typing import Optional, Set
from typing_extensions import Self

class IdentityEnrollmentsOttca(BaseModel):
    """
    IdentityEnrollmentsOttca
    """ # noqa: E501
    ca: Optional[EntityRef] = None
    ca_id: Optional[StrictStr] = Field(default=None, alias="caId")
    expires_at: Optional[datetime] = Field(default=None, alias="expiresAt")
    id: Optional[StrictStr] = None
    jwt: Optional[StrictStr] = None
    token: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["ca", "caId", "expiresAt", "id", "jwt", "token"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdentityEnrollmentsOttca from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ca
        if self.ca:
            _dict['ca'] = self.ca.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdentityEnrollmentsOttca from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ca": EntityRef.from_dict(obj["ca"]) if obj.get("ca") is not None else None,
            "caId": obj.get("caId"),
            "expiresAt": obj.get("expiresAt"),
            "id": obj.get("id"),
            "jwt": obj.get("jwt"),
            "token": obj.get("token")
        })
        return _obj


