# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_client.models.identity_enrollments_ott import IdentityEnrollmentsOtt
from openziti_edge_client.models.identity_enrollments_ottca import IdentityEnrollmentsOttca
from typing import Optional, Set
from typing_extensions import Self

class IdentityEnrollments(BaseModel):
    """
    IdentityEnrollments
    """ # noqa: E501
    ott: Optional[IdentityEnrollmentsOtt] = None
    ottca: Optional[IdentityEnrollmentsOttca] = None
    updb: Optional[IdentityEnrollmentsOtt] = None
    __properties: ClassVar[List[str]] = ["ott", "ottca", "updb"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdentityEnrollments from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ott
        if self.ott:
            _dict['ott'] = self.ott.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ottca
        if self.ottca:
            _dict['ottca'] = self.ottca.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updb
        if self.updb:
            _dict['updb'] = self.updb.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdentityEnrollments from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ott": IdentityEnrollmentsOtt.from_dict(obj["ott"]) if obj.get("ott") is not None else None,
            "ottca": IdentityEnrollmentsOttca.from_dict(obj["ottca"]) if obj.get("ottca") is not None else None,
            "updb": IdentityEnrollmentsOtt.from_dict(obj["updb"]) if obj.get("updb") is not None else None
        })
        return _obj


