# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PostureCheckType(str, Enum):
    """
    PostureCheckType
    """

    """
    allowed enum values
    """
    OS = 'OS'
    PROCESS = 'PROCESS'
    DOMAIN = 'DOMAIN'
    MAC = 'MAC'
    MFA = 'MFA'
    PROCESS_MULTI = 'PROCESS_MULTI'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PostureCheckType from a JSON string"""
        return cls(json.loads(json_str))


