# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_client.models.dial_bind import DialBind
from openziti_edge_client.models.link import Link
from openziti_edge_client.models.posture_queries import PostureQueries
from openziti_edge_client.models.tags import Tags
from typing import Optional, Set
from typing_extensions import Self

class ServiceDetail(BaseModel):
    """
    ServiceDetail
    """ # noqa: E501
    links: Dict[str, Link] = Field(description="A map of named links", alias="_links")
    created_at: datetime = Field(alias="createdAt")
    id: StrictStr
    tags: Optional[Tags] = None
    updated_at: datetime = Field(alias="updatedAt")
    config: Dict[str, Dict[str, Dict[str, Any]]] = Field(description="map of config data for this service keyed by the config type name. Only configs of the types requested will be returned.")
    configs: List[StrictStr]
    encryption_required: StrictBool = Field(description="Describes whether connections must support end-to-end encryption on both sides of the connection. Read-only property, set at create.", alias="encryptionRequired")
    max_idle_time_millis: StrictInt = Field(alias="maxIdleTimeMillis")
    name: StrictStr
    permissions: List[DialBind]
    posture_queries: List[PostureQueries] = Field(alias="postureQueries")
    role_attributes: Optional[List[StrictStr]] = Field(description="A set of strings used to loosely couple this resource to policies", alias="roleAttributes")
    terminator_strategy: StrictStr = Field(alias="terminatorStrategy")
    __properties: ClassVar[List[str]] = ["_links", "createdAt", "id", "tags", "updatedAt", "config", "configs", "encryptionRequired", "maxIdleTimeMillis", "name", "permissions", "postureQueries", "roleAttributes", "terminatorStrategy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in links (dict)
        _field_dict = {}
        if self.links:
            for _key_links in self.links:
                if self.links[_key_links]:
                    _field_dict[_key_links] = self.links[_key_links].to_dict()
            _dict['_links'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in posture_queries (list)
        _items = []
        if self.posture_queries:
            for _item_posture_queries in self.posture_queries:
                if _item_posture_queries:
                    _items.append(_item_posture_queries.to_dict())
            _dict['postureQueries'] = _items
        # set to None if role_attributes (nullable) is None
        # and model_fields_set contains the field
        if self.role_attributes is None and "role_attributes" in self.model_fields_set:
            _dict['roleAttributes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_links": dict(
                (_k, Link.from_dict(_v))
                for _k, _v in obj["_links"].items()
            )
            if obj.get("_links") is not None
            else None,
            "createdAt": obj.get("createdAt"),
            "id": obj.get("id"),
            "tags": Tags.from_dict(obj["tags"]) if obj.get("tags") is not None else None,
            "updatedAt": obj.get("updatedAt"),
            "config": obj.get("config"),
            "configs": obj.get("configs"),
            "encryptionRequired": obj.get("encryptionRequired"),
            "maxIdleTimeMillis": obj.get("maxIdleTimeMillis"),
            "name": obj.get("name"),
            "permissions": obj.get("permissions"),
            "postureQueries": [PostureQueries.from_dict(_item) for _item in obj["postureQueries"]] if obj.get("postureQueries") is not None else None,
            "roleAttributes": obj.get("roleAttributes"),
            "terminatorStrategy": obj.get("terminatorStrategy")
        })
        return _obj


