# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_client.models.api_version import ApiVersion
from typing import Optional, Set
from typing_extensions import Self

class Version(BaseModel):
    """
    Version
    """ # noqa: E501
    api_versions: Optional[Dict[str, Dict[str, ApiVersion]]] = Field(default=None, alias="apiVersions")
    build_date: Optional[StrictStr] = Field(default=None, alias="buildDate")
    capabilities: Optional[List[StrictStr]] = None
    revision: Optional[StrictStr] = None
    runtime_version: Optional[StrictStr] = Field(default=None, alias="runtimeVersion")
    version: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["apiVersions", "buildDate", "capabilities", "revision", "runtimeVersion", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Version from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in api_versions (dict)
        _field_dict = {}
        if self.api_versions:
            for _key_api_versions in self.api_versions:
                if self.api_versions[_key_api_versions]:
                    _field_dict[_key_api_versions] = self.api_versions[_key_api_versions].to_dict()
            _dict['apiVersions'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Version from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersions": dict(
                (_k, dict(
                    (_ik, ApiVersion.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj.get("apiVersions").items()
            )
            if obj.get("apiVersions") is not None
            else None,
            "buildDate": obj.get("buildDate"),
            "capabilities": obj.get("capabilities"),
            "revision": obj.get("revision"),
            "runtimeVersion": obj.get("runtimeVersion"),
            "version": obj.get("version")
        })
        return _obj


