# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AuthPolicyPrimaryUpdbPatch(BaseModel):
    """
    AuthPolicyPrimaryUpdbPatch
    """ # noqa: E501
    allowed: Optional[StrictBool] = None
    lockout_duration_minutes: Optional[StrictInt] = Field(default=None, alias="lockoutDurationMinutes")
    max_attempts: Optional[StrictInt] = Field(default=None, alias="maxAttempts")
    min_password_length: Optional[StrictInt] = Field(default=None, alias="minPasswordLength")
    require_mixed_case: Optional[StrictBool] = Field(default=None, alias="requireMixedCase")
    require_number_char: Optional[StrictBool] = Field(default=None, alias="requireNumberChar")
    require_special_char: Optional[StrictBool] = Field(default=None, alias="requireSpecialChar")
    __properties: ClassVar[List[str]] = ["allowed", "lockoutDurationMinutes", "maxAttempts", "minPasswordLength", "requireMixedCase", "requireNumberChar", "requireSpecialChar"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthPolicyPrimaryUpdbPatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if allowed (nullable) is None
        # and model_fields_set contains the field
        if self.allowed is None and "allowed" in self.model_fields_set:
            _dict['allowed'] = None

        # set to None if lockout_duration_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.lockout_duration_minutes is None and "lockout_duration_minutes" in self.model_fields_set:
            _dict['lockoutDurationMinutes'] = None

        # set to None if max_attempts (nullable) is None
        # and model_fields_set contains the field
        if self.max_attempts is None and "max_attempts" in self.model_fields_set:
            _dict['maxAttempts'] = None

        # set to None if min_password_length (nullable) is None
        # and model_fields_set contains the field
        if self.min_password_length is None and "min_password_length" in self.model_fields_set:
            _dict['minPasswordLength'] = None

        # set to None if require_mixed_case (nullable) is None
        # and model_fields_set contains the field
        if self.require_mixed_case is None and "require_mixed_case" in self.model_fields_set:
            _dict['requireMixedCase'] = None

        # set to None if require_number_char (nullable) is None
        # and model_fields_set contains the field
        if self.require_number_char is None and "require_number_char" in self.model_fields_set:
            _dict['requireNumberChar'] = None

        # set to None if require_special_char (nullable) is None
        # and model_fields_set contains the field
        if self.require_special_char is None and "require_special_char" in self.model_fields_set:
            _dict['requireSpecialChar'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthPolicyPrimaryUpdbPatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed": obj.get("allowed"),
            "lockoutDurationMinutes": obj.get("lockoutDurationMinutes"),
            "maxAttempts": obj.get("maxAttempts"),
            "minPasswordLength": obj.get("minPasswordLength"),
            "requireMixedCase": obj.get("requireMixedCase"),
            "requireNumberChar": obj.get("requireNumberChar"),
            "requireSpecialChar": obj.get("requireSpecialChar")
        })
        return _obj


