# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_management.models.external_id_claim_patch import ExternalIdClaimPatch
from openziti_edge_management.models.tags import Tags
from typing import Optional, Set
from typing_extensions import Self

class CaPatch(BaseModel):
    """
    CaPatch
    """ # noqa: E501
    external_id_claim: Optional[ExternalIdClaimPatch] = Field(default=None, alias="externalIdClaim")
    identity_name_format: Optional[StrictStr] = Field(default=None, alias="identityNameFormat")
    identity_roles: Optional[List[StrictStr]] = Field(default=None, alias="identityRoles")
    is_auth_enabled: Optional[StrictBool] = Field(default=None, alias="isAuthEnabled")
    is_auto_ca_enrollment_enabled: Optional[StrictBool] = Field(default=None, alias="isAutoCaEnrollmentEnabled")
    is_ott_ca_enrollment_enabled: Optional[StrictBool] = Field(default=None, alias="isOttCaEnrollmentEnabled")
    name: Optional[StrictStr] = None
    tags: Optional[Tags] = None
    __properties: ClassVar[List[str]] = ["externalIdClaim", "identityNameFormat", "identityRoles", "isAuthEnabled", "isAutoCaEnrollmentEnabled", "isOttCaEnrollmentEnabled", "name", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CaPatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of external_id_claim
        if self.external_id_claim:
            _dict['externalIdClaim'] = self.external_id_claim.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        # set to None if identity_name_format (nullable) is None
        # and model_fields_set contains the field
        if self.identity_name_format is None and "identity_name_format" in self.model_fields_set:
            _dict['identityNameFormat'] = None

        # set to None if is_auth_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.is_auth_enabled is None and "is_auth_enabled" in self.model_fields_set:
            _dict['isAuthEnabled'] = None

        # set to None if is_auto_ca_enrollment_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.is_auto_ca_enrollment_enabled is None and "is_auto_ca_enrollment_enabled" in self.model_fields_set:
            _dict['isAutoCaEnrollmentEnabled'] = None

        # set to None if is_ott_ca_enrollment_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.is_ott_ca_enrollment_enabled is None and "is_ott_ca_enrollment_enabled" in self.model_fields_set:
            _dict['isOttCaEnrollmentEnabled'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CaPatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "externalIdClaim": ExternalIdClaimPatch.from_dict(obj["externalIdClaim"]) if obj.get("externalIdClaim") is not None else None,
            "identityNameFormat": obj.get("identityNameFormat"),
            "identityRoles": obj.get("identityRoles"),
            "isAuthEnabled": obj.get("isAuthEnabled"),
            "isAutoCaEnrollmentEnabled": obj.get("isAutoCaEnrollmentEnabled"),
            "isOttCaEnrollmentEnabled": obj.get("isOttCaEnrollmentEnabled"),
            "name": obj.get("name"),
            "tags": Tags.from_dict(obj["tags"]) if obj.get("tags") is not None else None
        })
        return _obj


