# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_management.models.controller_settings import ControllerSettings
from openziti_edge_management.models.link import Link
from openziti_edge_management.models.tags import Tags
from typing import Optional, Set
from typing_extensions import Self

class ControllerSettingEffective(BaseModel):
    """
    ControllerSettingEffective
    """ # noqa: E501
    links: Dict[str, Link] = Field(description="A map of named links", alias="_links")
    created_at: datetime = Field(alias="createdAt")
    id: StrictStr
    tags: Optional[Tags] = None
    updated_at: datetime = Field(alias="updatedAt")
    effective: Optional[ControllerSettings] = None
    instance: Optional[ControllerSettings] = None
    __properties: ClassVar[List[str]] = ["_links", "createdAt", "id", "tags", "updatedAt", "effective", "instance"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ControllerSettingEffective from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in links (dict)
        _field_dict = {}
        if self.links:
            for _key_links in self.links:
                if self.links[_key_links]:
                    _field_dict[_key_links] = self.links[_key_links].to_dict()
            _dict['_links'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        # override the default output from pydantic by calling `to_dict()` of effective
        if self.effective:
            _dict['effective'] = self.effective.to_dict()
        # override the default output from pydantic by calling `to_dict()` of instance
        if self.instance:
            _dict['instance'] = self.instance.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ControllerSettingEffective from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_links": dict(
                (_k, Link.from_dict(_v))
                for _k, _v in obj["_links"].items()
            )
            if obj.get("_links") is not None
            else None,
            "createdAt": obj.get("createdAt"),
            "id": obj.get("id"),
            "tags": Tags.from_dict(obj["tags"]) if obj.get("tags") is not None else None,
            "updatedAt": obj.get("updatedAt"),
            "effective": ControllerSettings.from_dict(obj["effective"]) if obj.get("effective") is not None else None,
            "instance": ControllerSettings.from_dict(obj["instance"]) if obj.get("instance") is not None else None
        })
        return _obj


