# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ExternalIdClaim(BaseModel):
    """
    ExternalIdClaim
    """ # noqa: E501
    index: Optional[StrictInt]
    location: Optional[StrictStr]
    matcher: Optional[StrictStr]
    matcher_criteria: Optional[StrictStr] = Field(alias="matcherCriteria")
    parser: Optional[StrictStr]
    parser_criteria: Optional[StrictStr] = Field(alias="parserCriteria")
    __properties: ClassVar[List[str]] = ["index", "location", "matcher", "matcherCriteria", "parser", "parserCriteria"]

    @field_validator('location')
    def location_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['COMMON_NAME', 'SAN_URI', 'SAN_EMAIL']):
            raise ValueError("must be one of enum values ('COMMON_NAME', 'SAN_URI', 'SAN_EMAIL')")
        return value

    @field_validator('matcher')
    def matcher_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ALL', 'PREFIX', 'SUFFIX', 'SCHEME']):
            raise ValueError("must be one of enum values ('ALL', 'PREFIX', 'SUFFIX', 'SCHEME')")
        return value

    @field_validator('parser')
    def parser_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'SPLIT']):
            raise ValueError("must be one of enum values ('NONE', 'SPLIT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalIdClaim from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if index (nullable) is None
        # and model_fields_set contains the field
        if self.index is None and "index" in self.model_fields_set:
            _dict['index'] = None

        # set to None if location (nullable) is None
        # and model_fields_set contains the field
        if self.location is None and "location" in self.model_fields_set:
            _dict['location'] = None

        # set to None if matcher (nullable) is None
        # and model_fields_set contains the field
        if self.matcher is None and "matcher" in self.model_fields_set:
            _dict['matcher'] = None

        # set to None if matcher_criteria (nullable) is None
        # and model_fields_set contains the field
        if self.matcher_criteria is None and "matcher_criteria" in self.model_fields_set:
            _dict['matcherCriteria'] = None

        # set to None if parser (nullable) is None
        # and model_fields_set contains the field
        if self.parser is None and "parser" in self.model_fields_set:
            _dict['parser'] = None

        # set to None if parser_criteria (nullable) is None
        # and model_fields_set contains the field
        if self.parser_criteria is None and "parser_criteria" in self.model_fields_set:
            _dict['parserCriteria'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalIdClaim from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "index": obj.get("index"),
            "location": obj.get("location"),
            "matcher": obj.get("matcher"),
            "matcherCriteria": obj.get("matcherCriteria"),
            "parser": obj.get("parser"),
            "parserCriteria": obj.get("parserCriteria")
        })
        return _obj


