# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_management.models.dial_bind import DialBind
from openziti_edge_management.models.policy_failure import PolicyFailure
from typing import Optional, Set
from typing_extensions import Self

class FailedServiceRequest(BaseModel):
    """
    FailedServiceRequest
    """ # noqa: E501
    api_session_id: Optional[StrictStr] = Field(default=None, alias="apiSessionId")
    policy_failures: Optional[List[PolicyFailure]] = Field(default=None, alias="policyFailures")
    service_id: Optional[StrictStr] = Field(default=None, alias="serviceId")
    service_name: Optional[StrictStr] = Field(default=None, alias="serviceName")
    session_type: Optional[DialBind] = Field(default=None, alias="sessionType")
    when: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["apiSessionId", "policyFailures", "serviceId", "serviceName", "sessionType", "when"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FailedServiceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in policy_failures (list)
        _items = []
        if self.policy_failures:
            for _item_policy_failures in self.policy_failures:
                if _item_policy_failures:
                    _items.append(_item_policy_failures.to_dict())
            _dict['policyFailures'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FailedServiceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiSessionId": obj.get("apiSessionId"),
            "policyFailures": [PolicyFailure.from_dict(_item) for _item in obj["policyFailures"]] if obj.get("policyFailures") is not None else None,
            "serviceId": obj.get("serviceId"),
            "serviceName": obj.get("serviceName"),
            "sessionType": obj.get("sessionType"),
            "when": obj.get("when")
        })
        return _obj


