# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openziti_edge_management.models.entity_ref import EntityRef
from openziti_edge_management.models.router_entity_ref import RouterEntityRef
from typing import Optional, Set
from typing_extensions import Self

class PolicyAdvice(BaseModel):
    """
    PolicyAdvice
    """ # noqa: E501
    common_routers: Optional[List[RouterEntityRef]] = Field(default=None, alias="commonRouters")
    identity: Optional[EntityRef] = None
    identity_id: Optional[StrictStr] = Field(default=None, alias="identityId")
    identity_router_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="identityRouterCount")
    is_bind_allowed: Optional[StrictBool] = Field(default=None, alias="isBindAllowed")
    is_dial_allowed: Optional[StrictBool] = Field(default=None, alias="isDialAllowed")
    service: Optional[EntityRef] = None
    service_id: Optional[StrictStr] = Field(default=None, alias="serviceId")
    service_router_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="serviceRouterCount")
    __properties: ClassVar[List[str]] = ["commonRouters", "identity", "identityId", "identityRouterCount", "isBindAllowed", "isDialAllowed", "service", "serviceId", "serviceRouterCount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PolicyAdvice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in common_routers (list)
        _items = []
        if self.common_routers:
            for _item_common_routers in self.common_routers:
                if _item_common_routers:
                    _items.append(_item_common_routers.to_dict())
            _dict['commonRouters'] = _items
        # override the default output from pydantic by calling `to_dict()` of identity
        if self.identity:
            _dict['identity'] = self.identity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service
        if self.service:
            _dict['service'] = self.service.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PolicyAdvice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "commonRouters": [RouterEntityRef.from_dict(_item) for _item in obj["commonRouters"]] if obj.get("commonRouters") is not None else None,
            "identity": EntityRef.from_dict(obj["identity"]) if obj.get("identity") is not None else None,
            "identityId": obj.get("identityId"),
            "identityRouterCount": obj.get("identityRouterCount"),
            "isBindAllowed": obj.get("isBindAllowed"),
            "isDialAllowed": obj.get("isDialAllowed"),
            "service": EntityRef.from_dict(obj["service"]) if obj.get("service") is not None else None,
            "serviceId": obj.get("serviceId"),
            "serviceRouterCount": obj.get("serviceRouterCount")
        })
        return _obj


