# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openziti_edge_management.models.posture_check_type import PostureCheckType
from openziti_edge_management.models.tags import Tags
from typing import Optional, Set
from typing_extensions import Self

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from openziti_edge_management.models.posture_check_domain_patch import PostureCheckDomainPatch
    from openziti_edge_management.models.posture_check_mac_address_patch import PostureCheckMacAddressPatch
    from openziti_edge_management.models.posture_check_mfa_patch import PostureCheckMfaPatch
    from openziti_edge_management.models.posture_check_operating_system_patch import PostureCheckOperatingSystemPatch
    from openziti_edge_management.models.posture_check_process_multi_patch import PostureCheckProcessMultiPatch
    from openziti_edge_management.models.posture_check_process_patch import PostureCheckProcessPatch

class PostureCheckPatch(BaseModel):
    """
    PostureCheckPatch
    """ # noqa: E501
    name: Optional[StrictStr] = None
    role_attributes: Optional[List[StrictStr]] = Field(default=None, description="A set of strings used to loosely couple this resource to policies", alias="roleAttributes")
    tags: Optional[Tags] = None
    type_id: PostureCheckType = Field(alias="typeId")
    __properties: ClassVar[List[str]] = ["name", "roleAttributes", "tags", "typeId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = 'typeId'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'postureCheckDomainPatch': 'PostureCheckDomainPatch','postureCheckMacAddressPatch': 'PostureCheckMacAddressPatch','postureCheckMfaPatch': 'PostureCheckMfaPatch','postureCheckOperatingSystemPatch': 'PostureCheckOperatingSystemPatch','postureCheckProcessMultiPatch': 'PostureCheckProcessMultiPatch','postureCheckProcessPatch': 'PostureCheckProcessPatch'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[PostureCheckDomainPatch, PostureCheckMacAddressPatch, PostureCheckMfaPatch, PostureCheckOperatingSystemPatch, PostureCheckProcessMultiPatch, PostureCheckProcessPatch]]:
        """Create an instance of PostureCheckPatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        # set to None if role_attributes (nullable) is None
        # and model_fields_set contains the field
        if self.role_attributes is None and "role_attributes" in self.model_fields_set:
            _dict['roleAttributes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[Union[PostureCheckDomainPatch, PostureCheckMacAddressPatch, PostureCheckMfaPatch, PostureCheckOperatingSystemPatch, PostureCheckProcessMultiPatch, PostureCheckProcessPatch]]:
        """Create an instance of PostureCheckPatch from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type ==  'PostureCheckDomainPatch':
            return import_module("openziti_edge_management.models.posture_check_domain_patch").PostureCheckDomainPatch.from_dict(obj)
        if object_type ==  'PostureCheckMacAddressPatch':
            return import_module("openziti_edge_management.models.posture_check_mac_address_patch").PostureCheckMacAddressPatch.from_dict(obj)
        if object_type ==  'PostureCheckMfaPatch':
            return import_module("openziti_edge_management.models.posture_check_mfa_patch").PostureCheckMfaPatch.from_dict(obj)
        if object_type ==  'PostureCheckOperatingSystemPatch':
            return import_module("openziti_edge_management.models.posture_check_operating_system_patch").PostureCheckOperatingSystemPatch.from_dict(obj)
        if object_type ==  'PostureCheckProcessMultiPatch':
            return import_module("openziti_edge_management.models.posture_check_process_multi_patch").PostureCheckProcessMultiPatch.from_dict(obj)
        if object_type ==  'PostureCheckProcessPatch':
            return import_module("openziti_edge_management.models.posture_check_process_patch").PostureCheckProcessPatch.from_dict(obj)

        raise ValueError("PostureCheckPatch failed to lookup discriminator value from " +
                            json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                            ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


