# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_management.models.posture_check_patch import PostureCheckPatch
from openziti_edge_management.models.posture_check_type import PostureCheckType
from openziti_edge_management.models.tags import Tags
from typing import Optional, Set
from typing_extensions import Self

class PostureCheckMfaPatch(PostureCheckPatch):
    """
    PostureCheckMfaPatch
    """ # noqa: E501
    ignore_legacy_endpoints: Optional[StrictBool] = Field(default=None, alias="ignoreLegacyEndpoints")
    prompt_on_unlock: Optional[StrictBool] = Field(default=None, alias="promptOnUnlock")
    prompt_on_wake: Optional[StrictBool] = Field(default=None, alias="promptOnWake")
    timeout_seconds: Optional[StrictInt] = Field(default=None, alias="timeoutSeconds")
    __properties: ClassVar[List[str]] = ["name", "roleAttributes", "tags", "typeId", "ignoreLegacyEndpoints", "promptOnUnlock", "promptOnWake", "timeoutSeconds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostureCheckMfaPatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        # set to None if role_attributes (nullable) is None
        # and model_fields_set contains the field
        if self.role_attributes is None and "role_attributes" in self.model_fields_set:
            _dict['roleAttributes'] = None

        # set to None if ignore_legacy_endpoints (nullable) is None
        # and model_fields_set contains the field
        if self.ignore_legacy_endpoints is None and "ignore_legacy_endpoints" in self.model_fields_set:
            _dict['ignoreLegacyEndpoints'] = None

        # set to None if prompt_on_unlock (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_on_unlock is None and "prompt_on_unlock" in self.model_fields_set:
            _dict['promptOnUnlock'] = None

        # set to None if prompt_on_wake (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_on_wake is None and "prompt_on_wake" in self.model_fields_set:
            _dict['promptOnWake'] = None

        # set to None if timeout_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.timeout_seconds is None and "timeout_seconds" in self.model_fields_set:
            _dict['timeoutSeconds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostureCheckMfaPatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "roleAttributes": obj.get("roleAttributes"),
            "tags": Tags.from_dict(obj["tags"]) if obj.get("tags") is not None else None,
            "typeId": obj.get("typeId"),
            "ignoreLegacyEndpoints": obj.get("ignoreLegacyEndpoints"),
            "promptOnUnlock": obj.get("promptOnUnlock"),
            "promptOnWake": obj.get("promptOnWake"),
            "timeoutSeconds": obj.get("timeoutSeconds")
        })
        return _obj


