# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_management.models.dial_bind import DialBind
from openziti_edge_management.models.posture_query import PostureQuery
from typing import Optional, Set
from typing_extensions import Self

class PostureQueries(BaseModel):
    """
    PostureQueries
    """ # noqa: E501
    is_passing: StrictBool = Field(alias="isPassing")
    policy_id: StrictStr = Field(alias="policyId")
    policy_type: Optional[DialBind] = Field(default=None, alias="policyType")
    posture_queries: List[PostureQuery] = Field(alias="postureQueries")
    __properties: ClassVar[List[str]] = ["isPassing", "policyId", "policyType", "postureQueries"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostureQueries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in posture_queries (list)
        _items = []
        if self.posture_queries:
            for _item_posture_queries in self.posture_queries:
                if _item_posture_queries:
                    _items.append(_item_posture_queries.to_dict())
            _dict['postureQueries'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostureQueries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isPassing": obj.get("isPassing"),
            "policyId": obj.get("policyId"),
            "policyType": obj.get("policyType"),
            "postureQueries": [PostureQuery.from_dict(_item) for _item in obj["postureQueries"]] if obj.get("postureQueries") is not None else None
        })
        return _obj


