# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_management.models.dial_bind import DialBind
from openziti_edge_management.models.semantic import Semantic
from openziti_edge_management.models.tags import Tags
from typing import Optional, Set
from typing_extensions import Self

class ServicePolicyPatch(BaseModel):
    """
    ServicePolicyPatch
    """ # noqa: E501
    identity_roles: Optional[List[StrictStr]] = Field(default=None, alias="identityRoles")
    name: Optional[StrictStr] = None
    posture_check_roles: Optional[List[StrictStr]] = Field(default=None, alias="postureCheckRoles")
    semantic: Optional[Semantic] = None
    service_roles: Optional[List[StrictStr]] = Field(default=None, alias="serviceRoles")
    tags: Optional[Tags] = None
    type: Optional[DialBind] = None
    __properties: ClassVar[List[str]] = ["identityRoles", "name", "postureCheckRoles", "semantic", "serviceRoles", "tags", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServicePolicyPatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServicePolicyPatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identityRoles": obj.get("identityRoles"),
            "name": obj.get("name"),
            "postureCheckRoles": obj.get("postureCheckRoles"),
            "semantic": obj.get("semantic"),
            "serviceRoles": obj.get("serviceRoles"),
            "tags": Tags.from_dict(obj["tags"]) if obj.get("tags") is not None else None,
            "type": obj.get("type")
        })
        return _obj


