# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openziti_edge_management.models.tags import Tags
from typing import Optional, Set
from typing_extensions import Self

class ServicePatch(BaseModel):
    """
    ServicePatch
    """ # noqa: E501
    configs: Optional[List[StrictStr]] = None
    encryption_required: Optional[StrictBool] = Field(default=None, description="Describes whether connections must support end-to-end encryption on both sides of the connection. Read-only property, set at create.", alias="encryptionRequired")
    max_idle_time_millis: Optional[StrictInt] = Field(default=None, alias="maxIdleTimeMillis")
    name: Optional[StrictStr] = None
    role_attributes: Optional[List[StrictStr]] = Field(default=None, alias="roleAttributes")
    tags: Optional[Tags] = None
    terminator_strategy: Optional[StrictStr] = Field(default=None, alias="terminatorStrategy")
    __properties: ClassVar[List[str]] = ["configs", "encryptionRequired", "maxIdleTimeMillis", "name", "roleAttributes", "tags", "terminatorStrategy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServicePatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServicePatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configs": obj.get("configs"),
            "encryptionRequired": obj.get("encryptionRequired"),
            "maxIdleTimeMillis": obj.get("maxIdleTimeMillis"),
            "name": obj.get("name"),
            "roleAttributes": obj.get("roleAttributes"),
            "tags": Tags.from_dict(obj["tags"]) if obj.get("tags") is not None else None,
            "terminatorStrategy": obj.get("terminatorStrategy")
        })
        return _obj


