# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.current_identity_edge_router_detail import CurrentIdentityEdgeRouterDetail

class TestCurrentIdentityEdgeRouterDetail(unittest.TestCase):
    """CurrentIdentityEdgeRouterDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CurrentIdentityEdgeRouterDetail:
        """Test CurrentIdentityEdgeRouterDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CurrentIdentityEdgeRouterDetail`
        """
        model = CurrentIdentityEdgeRouterDetail()
        if include_optional:
            return CurrentIdentityEdgeRouterDetail(
                links = {
                    'key' : openziti_edge_client.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                tags = None,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                app_data = None,
                cost = 0,
                disabled = True,
                hostname = '',
                is_online = True,
                name = '',
                no_traversal = True,
                supported_protocols = {
                    'key' : ''
                    },
                sync_status = ''
            )
        else:
            return CurrentIdentityEdgeRouterDetail(
                links = {
                    'key' : openziti_edge_client.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cost = 0,
                disabled = True,
                hostname = '',
                is_online = True,
                name = '',
                no_traversal = True,
                supported_protocols = {
                    'key' : ''
                    },
                sync_status = '',
        )
        """

    def testCurrentIdentityEdgeRouterDetail(self):
        """Test CurrentIdentityEdgeRouterDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
