# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.identity_enrollments_ottca import IdentityEnrollmentsOttca

class TestIdentityEnrollmentsOttca(unittest.TestCase):
    """IdentityEnrollmentsOttca unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityEnrollmentsOttca:
        """Test IdentityEnrollmentsOttca
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityEnrollmentsOttca`
        """
        model = IdentityEnrollmentsOttca()
        if include_optional:
            return IdentityEnrollmentsOttca(
                ca = openziti_edge_client.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_client.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                ca_id = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                jwt = '',
                token = ''
            )
        else:
            return IdentityEnrollmentsOttca(
        )
        """

    def testIdentityEnrollmentsOttca(self):
        """Test IdentityEnrollmentsOttca"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
