# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.current_api_session_certificate_create_response import CurrentApiSessionCertificateCreateResponse

class TestCurrentApiSessionCertificateCreateResponse(unittest.TestCase):
    """CurrentApiSessionCertificateCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CurrentApiSessionCertificateCreateResponse:
        """Test CurrentApiSessionCertificateCreateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CurrentApiSessionCertificateCreateResponse`
        """
        model = CurrentApiSessionCertificateCreateResponse()
        if include_optional:
            return CurrentApiSessionCertificateCreateResponse(
                links = {
                    'key' : openziti_edge_client.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                id = '',
                cas = '',
                certificate = ''
            )
        else:
            return CurrentApiSessionCertificateCreateResponse(
                certificate = '',
        )
        """

    def testCurrentApiSessionCertificateCreateResponse(self):
        """Test CurrentApiSessionCertificateCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
