# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.list_protocols_envelope import ListProtocolsEnvelope

class TestListProtocolsEnvelope(unittest.TestCase):
    """ListProtocolsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListProtocolsEnvelope:
        """Test ListProtocolsEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListProtocolsEnvelope`
        """
        model = ListProtocolsEnvelope()
        if include_optional:
            return ListProtocolsEnvelope(
                data = {
                    'key' : openziti_edge_client.models.protocol.protocol(
                        address = '', )
                    },
                meta = openziti_edge_client.models.meta.meta(
                    api_enrollment_version = '', 
                    api_version = '', 
                    filterable_fields = [
                        ''
                        ], 
                    pagination = openziti_edge_client.models.pagination.pagination(
                        limit = 1.337, 
                        offset = 1.337, 
                        total_count = 1.337, ), )
            )
        else:
            return ListProtocolsEnvelope(
                data = {
                    'key' : openziti_edge_client.models.protocol.protocol(
                        address = '', )
                    },
                meta = openziti_edge_client.models.meta.meta(
                    api_enrollment_version = '', 
                    api_version = '', 
                    filterable_fields = [
                        ''
                        ], 
                    pagination = openziti_edge_client.models.pagination.pagination(
                        limit = 1.337, 
                        offset = 1.337, 
                        total_count = 1.337, ), ),
        )
        """

    def testListProtocolsEnvelope(self):
        """Test ListProtocolsEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
