# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.generic_enroll import GenericEnroll

class TestGenericEnroll(unittest.TestCase):
    """GenericEnroll unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenericEnroll:
        """Test GenericEnroll
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenericEnroll`
        """
        model = GenericEnroll()
        if include_optional:
            return GenericEnroll(
                cert_csr = '',
                client_csr = '',
                name = '',
                password = '01234',
                server_cert_csr = '',
                username = '0123'
            )
        else:
            return GenericEnroll(
        )
        """

    def testGenericEnroll(self):
        """Test GenericEnroll"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
