# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.posture_check_type import PostureCheckType

class TestPostureCheckType(unittest.TestCase):
    """PostureCheckType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckType(self):
        """Test PostureCheckType"""
        # inst = PostureCheckType()

if __name__ == '__main__':
    unittest.main()
