# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.api.enrollment_api import EnrollmentApi


class TestEnrollmentApi(unittest.TestCase):
    """EnrollmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnrollmentApi()

    def tearDown(self) -> None:
        pass

    def test_list_network_jwts(self) -> None:
        """Test case for list_network_jwts

        Returns a list of JWTs suitable for bootstrapping network trust.
        """
        pass


if __name__ == '__main__':
    unittest.main()
