# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.identity_authenticators import IdentityAuthenticators

class TestIdentityAuthenticators(unittest.TestCase):
    """IdentityAuthenticators unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityAuthenticators:
        """Test IdentityAuthenticators
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityAuthenticators`
        """
        model = IdentityAuthenticators()
        if include_optional:
            return IdentityAuthenticators(
                cert = openziti_edge_client.models.identity_authenticators_cert.identityAuthenticators_cert(
                    fingerprint = '', 
                    id = '', ),
                updb = openziti_edge_client.models.identity_authenticators_updb.identityAuthenticators_updb(
                    id = '', 
                    username = '', )
            )
        else:
            return IdentityAuthenticators(
        )
        """

    def testIdentityAuthenticators(self):
        """Test IdentityAuthenticators"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
