# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.interface import Interface

class TestInterface(unittest.TestCase):
    """Interface unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Interface:
        """Test Interface
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Interface`
        """
        model = Interface()
        if include_optional:
            return Interface(
                addresses = [
                    ''
                    ],
                hardware_address = '',
                index = 0,
                is_broadcast = True,
                is_loopback = True,
                is_multicast = True,
                is_running = True,
                is_up = True,
                mtu = 0,
                name = ''
            )
        else:
            return Interface(
                hardware_address = '',
                index = 0,
                is_broadcast = True,
                is_loopback = True,
                is_multicast = True,
                is_running = True,
                is_up = True,
                mtu = 0,
                name = '',
        )
        """

    def testInterface(self):
        """Test Interface"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
