# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.posture_response_service import PostureResponseService

class TestPostureResponseService(unittest.TestCase):
    """PostureResponseService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostureResponseService:
        """Test PostureResponseService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostureResponseService`
        """
        model = PostureResponseService()
        if include_optional:
            return PostureResponseService(
                id = '',
                name = '',
                posture_query_type = '',
                timeout = 56,
                timeout_remaining = 56
            )
        else:
            return PostureResponseService(
                id = '',
                name = '',
                posture_query_type = '',
                timeout = 56,
                timeout_remaining = 56,
        )
        """

    def testPostureResponseService(self):
        """Test PostureResponseService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
