# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.identity_enrollments_ott import IdentityEnrollmentsOtt

class TestIdentityEnrollmentsOtt(unittest.TestCase):
    """IdentityEnrollmentsOtt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityEnrollmentsOtt:
        """Test IdentityEnrollmentsOtt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityEnrollmentsOtt`
        """
        model = IdentityEnrollmentsOtt()
        if include_optional:
            return IdentityEnrollmentsOtt(
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                jwt = '',
                token = ''
            )
        else:
            return IdentityEnrollmentsOtt(
        )
        """

    def testIdentityEnrollmentsOtt(self):
        """Test IdentityEnrollmentsOtt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
