# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.session_create import SessionCreate

class TestSessionCreate(unittest.TestCase):
    """SessionCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionCreate:
        """Test SessionCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionCreate`
        """
        model = SessionCreate()
        if include_optional:
            return SessionCreate(
                service_id = '',
                tags = None,
                type = 'Dial'
            )
        else:
            return SessionCreate(
        )
        """

    def testSessionCreate(self):
        """Test SessionCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
