# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.api.enroll_api import EnrollApi


class TestEnrollApi(unittest.TestCase):
    """EnrollApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnrollApi()

    def tearDown(self) -> None:
        pass

    def test_enroll(self) -> None:
        """Test case for enroll

        Enroll an identity via one-time-token
        """
        pass

    def test_enroll_ca(self) -> None:
        """Test case for enroll_ca

        Enroll an identity with a pre-exchanged certificate
        """
        pass

    def test_enroll_er_ott(self) -> None:
        """Test case for enroll_er_ott

        Enroll an edge-router
        """
        pass

    def test_enroll_ott(self) -> None:
        """Test case for enroll_ott

        Enroll an identity via one-time-token
        """
        pass

    def test_enroll_ott_ca(self) -> None:
        """Test case for enroll_ott_ca

        Enroll an identity via one-time-token with a pre-exchanged client certificate
        """
        pass

    def test_enroll_token(self) -> None:
        """Test case for enroll_token

        """
        pass

    def test_enroll_updb(self) -> None:
        """Test case for enroll_updb

        Enroll an identity via one-time-token
        """
        pass

    def test_enrollment_challenge(self) -> None:
        """Test case for enrollment_challenge

        Allows verification of a controller or cluster of controllers as being the valid target for enrollment.
        """
        pass

    def test_extend_current_identity_authenticator(self) -> None:
        """Test case for extend_current_identity_authenticator

        Allows the current identity to recieve a new certificate associated with a certificate based authenticator
        """
        pass

    def test_extend_router_enrollment(self) -> None:
        """Test case for extend_router_enrollment

        Extend the life of a currently enrolled router's certificates
        """
        pass

    def test_extend_verify_current_identity_authenticator(self) -> None:
        """Test case for extend_verify_current_identity_authenticator

        Allows the current identity to validate reciept of a new client certificate
        """
        pass

    def test_get_enrollment_jwks(self) -> None:
        """Test case for get_enrollment_jwks

        List JSON Web Keys associated with enrollment
        """
        pass


if __name__ == '__main__':
    unittest.main()
