# coding: utf-8

"""
    Ziti Edge Client

    OpenZiti Edge Client API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_client.models.service_update import ServiceUpdate

class TestServiceUpdate(unittest.TestCase):
    """ServiceUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceUpdate:
        """Test ServiceUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceUpdate`
        """
        model = ServiceUpdate()
        if include_optional:
            return ServiceUpdate(
                configs = [
                    ''
                    ],
                encryption_required = True,
                max_idle_time_millis = 56,
                name = '',
                role_attributes = [
                    ''
                    ],
                tags = None,
                terminator_strategy = ''
            )
        else:
            return ServiceUpdate(
                name = '',
        )
        """

    def testServiceUpdate(self):
        """Test ServiceUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
