# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.posture_check_failure_process import PostureCheckFailureProcess

class TestPostureCheckFailureProcess(unittest.TestCase):
    """PostureCheckFailureProcess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostureCheckFailureProcess:
        """Test PostureCheckFailureProcess
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostureCheckFailureProcess`
        """
        model = PostureCheckFailureProcess()
        if include_optional:
            return PostureCheckFailureProcess(
                actual_value = openziti_edge_management.models.posture_check_failure_process_actual.postureCheckFailureProcessActual(
                    hash = '', 
                    is_running = True, 
                    os_type = 'Windows', 
                    path = '', 
                    signer_fingerprints = [
                        ''
                        ], ),
                expected_value = openziti_edge_management.models.process.process(
                    hashes = [
                        ''
                        ], 
                    os_type = 'Windows', 
                    path = '', 
                    signer_fingerprint = '', )
            )
        else:
            return PostureCheckFailureProcess(
                actual_value = openziti_edge_management.models.posture_check_failure_process_actual.postureCheckFailureProcessActual(
                    hash = '', 
                    is_running = True, 
                    os_type = 'Windows', 
                    path = '', 
                    signer_fingerprints = [
                        ''
                        ], ),
                expected_value = openziti_edge_management.models.process.process(
                    hashes = [
                        ''
                        ], 
                    os_type = 'Windows', 
                    path = '', 
                    signer_fingerprint = '', ),
        )
        """

    def testPostureCheckFailureProcess(self):
        """Test PostureCheckFailureProcess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
