# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.controller_settings_oidc import ControllerSettingsOidc

class TestControllerSettingsOidc(unittest.TestCase):
    """ControllerSettingsOidc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ControllerSettingsOidc:
        """Test ControllerSettingsOidc
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ControllerSettingsOidc`
        """
        model = ControllerSettingsOidc()
        if include_optional:
            return ControllerSettingsOidc(
                post_logout_uris = [
                    ''
                    ],
                redirect_uris = [
                    ''
                    ]
            )
        else:
            return ControllerSettingsOidc(
        )
        """

    def testControllerSettingsOidc(self):
        """Test ControllerSettingsOidc"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
