# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.terminator_patch import TerminatorPatch

class TestTerminatorPatch(unittest.TestCase):
    """TerminatorPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerminatorPatch:
        """Test TerminatorPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerminatorPatch`
        """
        model = TerminatorPatch()
        if include_optional:
            return TerminatorPatch(
                address = '',
                binding = '',
                cost = 0,
                precedence = 'default',
                router = '',
                service = '',
                tags = None
            )
        else:
            return TerminatorPatch(
        )
        """

    def testTerminatorPatch(self):
        """Test TerminatorPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
