# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.data_integrity_check_details import DataIntegrityCheckDetails

class TestDataIntegrityCheckDetails(unittest.TestCase):
    """DataIntegrityCheckDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataIntegrityCheckDetails:
        """Test DataIntegrityCheckDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataIntegrityCheckDetails`
        """
        model = DataIntegrityCheckDetails()
        if include_optional:
            return DataIntegrityCheckDetails(
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error = '',
                fixing_errors = True,
                in_progress = True,
                results = [
                    openziti_edge_management.models.data_integrity_check_detail.dataIntegrityCheckDetail(
                        description = '', 
                        fixed = True, )
                    ],
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                too_many_errors = True
            )
        else:
            return DataIntegrityCheckDetails(
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error = '',
                fixing_errors = True,
                in_progress = True,
                results = [
                    openziti_edge_management.models.data_integrity_check_detail.dataIntegrityCheckDetail(
                        description = '', 
                        fixed = True, )
                    ],
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                too_many_errors = True,
        )
        """

    def testDataIntegrityCheckDetails(self):
        """Test DataIntegrityCheckDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
