# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.identity_create import IdentityCreate

class TestIdentityCreate(unittest.TestCase):
    """IdentityCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityCreate:
        """Test IdentityCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityCreate`
        """
        model = IdentityCreate()
        if include_optional:
            return IdentityCreate(
                app_data = None,
                auth_policy_id = '',
                default_hosting_cost = 0,
                default_hosting_precedence = 'default',
                enrollment = openziti_edge_management.models.identity_create_enrollment.identityCreate_enrollment(
                    ott = True, 
                    ottca = '', 
                    updb = '', ),
                external_id = '',
                is_admin = True,
                name = '',
                permissions = [
                    'admin_readonly'
                    ],
                role_attributes = [
                    ''
                    ],
                service_hosting_costs = {
                    'key' : 0
                    },
                service_hosting_precedences = {
                    'key' : 'default'
                    },
                tags = None,
                type = 'User'
            )
        else:
            return IdentityCreate(
                is_admin = True,
                name = '',
                type = 'User',
        )
        """

    def testIdentityCreate(self):
        """Test IdentityCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
