# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.auth_policy_detail import AuthPolicyDetail

class TestAuthPolicyDetail(unittest.TestCase):
    """AuthPolicyDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthPolicyDetail:
        """Test AuthPolicyDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthPolicyDetail`
        """
        model = AuthPolicyDetail()
        if include_optional:
            return AuthPolicyDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                tags = None,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                primary = openziti_edge_management.models.auth_policy_primary.authPolicyPrimary(
                    cert = openziti_edge_management.models.auth_policy_primary_cert.authPolicyPrimaryCert(
                        allow_expired_certs = True, 
                        allowed = True, ), 
                    ext_jwt = openziti_edge_management.models.auth_policy_primary_ext_jwt.authPolicyPrimaryExtJwt(
                        allowed = True, 
                        allowed_signers = [
                            ''
                            ], ), 
                    updb = openziti_edge_management.models.auth_policy_primary_updb.authPolicyPrimaryUpdb(
                        allowed = True, 
                        lockout_duration_minutes = 56, 
                        max_attempts = 56, 
                        min_password_length = 56, 
                        require_mixed_case = True, 
                        require_number_char = True, 
                        require_special_char = True, ), ),
                secondary = openziti_edge_management.models.auth_policy_secondary.authPolicySecondary(
                    require_ext_jwt_signer = '', 
                    require_totp = True, )
            )
        else:
            return AuthPolicyDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                primary = openziti_edge_management.models.auth_policy_primary.authPolicyPrimary(
                    cert = openziti_edge_management.models.auth_policy_primary_cert.authPolicyPrimaryCert(
                        allow_expired_certs = True, 
                        allowed = True, ), 
                    ext_jwt = openziti_edge_management.models.auth_policy_primary_ext_jwt.authPolicyPrimaryExtJwt(
                        allowed = True, 
                        allowed_signers = [
                            ''
                            ], ), 
                    updb = openziti_edge_management.models.auth_policy_primary_updb.authPolicyPrimaryUpdb(
                        allowed = True, 
                        lockout_duration_minutes = 56, 
                        max_attempts = 56, 
                        min_password_length = 56, 
                        require_mixed_case = True, 
                        require_number_char = True, 
                        require_special_char = True, ), ),
                secondary = openziti_edge_management.models.auth_policy_secondary.authPolicySecondary(
                    require_ext_jwt_signer = '', 
                    require_totp = True, ),
        )
        """

    def testAuthPolicyDetail(self):
        """Test AuthPolicyDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
