# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.auth_policy_primary_ext_jwt_patch import AuthPolicyPrimaryExtJwtPatch

class TestAuthPolicyPrimaryExtJwtPatch(unittest.TestCase):
    """AuthPolicyPrimaryExtJwtPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthPolicyPrimaryExtJwtPatch:
        """Test AuthPolicyPrimaryExtJwtPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthPolicyPrimaryExtJwtPatch`
        """
        model = AuthPolicyPrimaryExtJwtPatch()
        if include_optional:
            return AuthPolicyPrimaryExtJwtPatch(
                allowed = True,
                allowed_signers = [
                    ''
                    ]
            )
        else:
            return AuthPolicyPrimaryExtJwtPatch(
        )
        """

    def testAuthPolicyPrimaryExtJwtPatch(self):
        """Test AuthPolicyPrimaryExtJwtPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
