# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.posture_check_process_multi_update import PostureCheckProcessMultiUpdate

class TestPostureCheckProcessMultiUpdate(unittest.TestCase):
    """PostureCheckProcessMultiUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostureCheckProcessMultiUpdate:
        """Test PostureCheckProcessMultiUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostureCheckProcessMultiUpdate`
        """
        model = PostureCheckProcessMultiUpdate()
        if include_optional:
            return PostureCheckProcessMultiUpdate(
                processes = [
                    openziti_edge_management.models.process_multi.processMulti(
                        hashes = [
                            ''
                            ], 
                        os_type = 'Windows', 
                        path = '', 
                        signer_fingerprints = [
                            ''
                            ], )
                    ],
                semantic = 'AllOf'
            )
        else:
            return PostureCheckProcessMultiUpdate(
                processes = [
                    openziti_edge_management.models.process_multi.processMulti(
                        hashes = [
                            ''
                            ], 
                        os_type = 'Windows', 
                        path = '', 
                        signer_fingerprints = [
                            ''
                            ], )
                    ],
                semantic = 'AllOf',
        )
        """

    def testPostureCheckProcessMultiUpdate(self):
        """Test PostureCheckProcessMultiUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
