# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.api.database_api import DatabaseApi


class TestDatabaseApi(unittest.TestCase):
    """DatabaseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatabaseApi()

    def tearDown(self) -> None:
        pass

    def test_check_data_integrity(self) -> None:
        """Test case for check_data_integrity

        Starts a data integrity scan on the datastore
        """
        pass

    def test_create_database_snapshot(self) -> None:
        """Test case for create_database_snapshot

        Create a new database snapshot
        """
        pass

    def test_data_integrity_results(self) -> None:
        """Test case for data_integrity_results

        Returns any results found from in-progress integrity checks
        """
        pass

    def test_fix_data_integrity(self) -> None:
        """Test case for fix_data_integrity

        Runs a data integrity scan on the datastore, attempts to fix any issues it can and returns any found issues
        """
        pass


if __name__ == '__main__':
    unittest.main()
