# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.auth_policy_primary_patch import AuthPolicyPrimaryPatch

class TestAuthPolicyPrimaryPatch(unittest.TestCase):
    """AuthPolicyPrimaryPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthPolicyPrimaryPatch:
        """Test AuthPolicyPrimaryPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthPolicyPrimaryPatch`
        """
        model = AuthPolicyPrimaryPatch()
        if include_optional:
            return AuthPolicyPrimaryPatch(
                cert = openziti_edge_management.models.auth_policy_primary_cert_patch.authPolicyPrimaryCertPatch(
                    allow_expired_certs = True, 
                    allowed = True, ),
                ext_jwt = openziti_edge_management.models.auth_policy_primary_ext_jwt_patch.authPolicyPrimaryExtJwtPatch(
                    allowed = True, 
                    allowed_signers = [
                        ''
                        ], ),
                updb = openziti_edge_management.models.auth_policy_primary_updb_patch.authPolicyPrimaryUpdbPatch(
                    allowed = True, 
                    lockout_duration_minutes = 56, 
                    max_attempts = 56, 
                    min_password_length = 56, 
                    require_mixed_case = True, 
                    require_number_char = True, 
                    require_special_char = True, )
            )
        else:
            return AuthPolicyPrimaryPatch(
        )
        """

    def testAuthPolicyPrimaryPatch(self):
        """Test AuthPolicyPrimaryPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
