# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.api.service_edge_router_policy_api import ServiceEdgeRouterPolicyApi


class TestServiceEdgeRouterPolicyApi(unittest.TestCase):
    """ServiceEdgeRouterPolicyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceEdgeRouterPolicyApi()

    def tearDown(self) -> None:
        pass

    def test_create_service_edge_router_policy(self) -> None:
        """Test case for create_service_edge_router_policy

        Create a service edge router policy resource
        """
        pass

    def test_delete_service_edge_router_policy(self) -> None:
        """Test case for delete_service_edge_router_policy

        Delete a service edge policy
        """
        pass

    def test_detail_service_edge_router_policy(self) -> None:
        """Test case for detail_service_edge_router_policy

        Retrieves a single service edge policy
        """
        pass

    def test_list_service_edge_router_policies(self) -> None:
        """Test case for list_service_edge_router_policies

        List service edge router policies
        """
        pass

    def test_list_service_edge_router_policy_edge_routers(self) -> None:
        """Test case for list_service_edge_router_policy_edge_routers

        List the edge routers that a service edge router policy applies to
        """
        pass

    def test_list_service_edge_router_policy_services(self) -> None:
        """Test case for list_service_edge_router_policy_services

        List the services that a service edge router policy applies to
        """
        pass

    def test_patch_service_edge_router_policy(self) -> None:
        """Test case for patch_service_edge_router_policy

        Update the supplied fields on a service edge policy
        """
        pass

    def test_update_service_edge_router_policy(self) -> None:
        """Test case for update_service_edge_router_policy

        Update all fields on a service edge policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
