# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.create_location import CreateLocation

class TestCreateLocation(unittest.TestCase):
    """CreateLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateLocation:
        """Test CreateLocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateLocation`
        """
        model = CreateLocation()
        if include_optional:
            return CreateLocation(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                id = ''
            )
        else:
            return CreateLocation(
        )
        """

    def testCreateLocation(self):
        """Test CreateLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
