# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.service_edge_router_policy_patch import ServiceEdgeRouterPolicyPatch

class TestServiceEdgeRouterPolicyPatch(unittest.TestCase):
    """ServiceEdgeRouterPolicyPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceEdgeRouterPolicyPatch:
        """Test ServiceEdgeRouterPolicyPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceEdgeRouterPolicyPatch`
        """
        model = ServiceEdgeRouterPolicyPatch()
        if include_optional:
            return ServiceEdgeRouterPolicyPatch(
                edge_router_roles = [
                    ''
                    ],
                name = '',
                semantic = 'AllOf',
                service_roles = [
                    ''
                    ],
                tags = None
            )
        else:
            return ServiceEdgeRouterPolicyPatch(
        )
        """

    def testServiceEdgeRouterPolicyPatch(self):
        """Test ServiceEdgeRouterPolicyPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
