# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.mfa_providers import MfaProviders

class TestMfaProviders(unittest.TestCase):
    """MfaProviders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMfaProviders(self):
        """Test MfaProviders"""
        # inst = MfaProviders()

if __name__ == '__main__':
    unittest.main()
