# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.failed_service_request_envelope import FailedServiceRequestEnvelope

class TestFailedServiceRequestEnvelope(unittest.TestCase):
    """FailedServiceRequestEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FailedServiceRequestEnvelope:
        """Test FailedServiceRequestEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FailedServiceRequestEnvelope`
        """
        model = FailedServiceRequestEnvelope()
        if include_optional:
            return FailedServiceRequestEnvelope(
                data = [
                    openziti_edge_management.models.failed_service_request.failedServiceRequest(
                        api_session_id = '', 
                        policy_failures = [
                            openziti_edge_management.models.policy_failure.policyFailure(
                                checks = [
                                    openziti_edge_management.models.posture_check_failure.postureCheckFailure(
                                        posture_check_id = '', 
                                        posture_check_name = '', 
                                        posture_check_type = '', )
                                    ], 
                                policy_id = '', 
                                policy_name = '', )
                            ], 
                        service_id = '', 
                        service_name = '', 
                        session_type = 'Dial', 
                        when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                meta = openziti_edge_management.models.meta.meta(
                    api_enrollment_version = '', 
                    api_version = '', 
                    filterable_fields = [
                        ''
                        ], 
                    pagination = openziti_edge_management.models.pagination.pagination(
                        limit = 1.337, 
                        offset = 1.337, 
                        total_count = 1.337, ), )
            )
        else:
            return FailedServiceRequestEnvelope(
                data = [
                    openziti_edge_management.models.failed_service_request.failedServiceRequest(
                        api_session_id = '', 
                        policy_failures = [
                            openziti_edge_management.models.policy_failure.policyFailure(
                                checks = [
                                    openziti_edge_management.models.posture_check_failure.postureCheckFailure(
                                        posture_check_id = '', 
                                        posture_check_name = '', 
                                        posture_check_type = '', )
                                    ], 
                                policy_id = '', 
                                policy_name = '', )
                            ], 
                        service_id = '', 
                        service_name = '', 
                        session_type = 'Dial', 
                        when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                meta = openziti_edge_management.models.meta.meta(
                    api_enrollment_version = '', 
                    api_version = '', 
                    filterable_fields = [
                        ''
                        ], 
                    pagination = openziti_edge_management.models.pagination.pagination(
                        limit = 1.337, 
                        offset = 1.337, 
                        total_count = 1.337, ), ),
        )
        """

    def testFailedServiceRequestEnvelope(self):
        """Test FailedServiceRequestEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
