# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.detail_enrollment_envelope import DetailEnrollmentEnvelope

class TestDetailEnrollmentEnvelope(unittest.TestCase):
    """DetailEnrollmentEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetailEnrollmentEnvelope:
        """Test DetailEnrollmentEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetailEnrollmentEnvelope`
        """
        model = DetailEnrollmentEnvelope()
        if include_optional:
            return DetailEnrollmentEnvelope(
                data = None,
                meta = openziti_edge_management.models.meta.meta(
                    api_enrollment_version = '', 
                    api_version = '', 
                    filterable_fields = [
                        ''
                        ], 
                    pagination = openziti_edge_management.models.pagination.pagination(
                        limit = 1.337, 
                        offset = 1.337, 
                        total_count = 1.337, ), )
            )
        else:
            return DetailEnrollmentEnvelope(
                data = None,
                meta = openziti_edge_management.models.meta.meta(
                    api_enrollment_version = '', 
                    api_version = '', 
                    filterable_fields = [
                        ''
                        ], 
                    pagination = openziti_edge_management.models.pagination.pagination(
                        limit = 1.337, 
                        offset = 1.337, 
                        total_count = 1.337, ), ),
        )
        """

    def testDetailEnrollmentEnvelope(self):
        """Test DetailEnrollmentEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
