# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.api.router_api import RouterApi


class TestRouterApi(unittest.TestCase):
    """RouterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RouterApi()

    def tearDown(self) -> None:
        pass

    def test_create_router(self) -> None:
        """Test case for create_router

        Create a router resource
        """
        pass

    def test_create_transit_router(self) -> None:
        """Test case for create_transit_router

        Create a router resource
        """
        pass

    def test_delete_router(self) -> None:
        """Test case for delete_router

        Delete a router
        """
        pass

    def test_delete_transit_router(self) -> None:
        """Test case for delete_transit_router

        Delete a router
        """
        pass

    def test_detail_router(self) -> None:
        """Test case for detail_router

        Retrieves a single router
        """
        pass

    def test_detail_transit_router(self) -> None:
        """Test case for detail_transit_router

        Retrieves a single router
        """
        pass

    def test_list_routers(self) -> None:
        """Test case for list_routers

        List routers
        """
        pass

    def test_list_transit_routers(self) -> None:
        """Test case for list_transit_routers

        List routers
        """
        pass

    def test_patch_router(self) -> None:
        """Test case for patch_router

        Update the supplied fields on a router
        """
        pass

    def test_patch_transit_router(self) -> None:
        """Test case for patch_transit_router

        Update the supplied fields on a router
        """
        pass

    def test_update_router(self) -> None:
        """Test case for update_router

        Update all fields on a router
        """
        pass

    def test_update_transit_router(self) -> None:
        """Test case for update_transit_router

        Update all fields on a router
        """
        pass


if __name__ == '__main__':
    unittest.main()
