# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.posture_data_os import PostureDataOs

class TestPostureDataOs(unittest.TestCase):
    """PostureDataOs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostureDataOs:
        """Test PostureDataOs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostureDataOs`
        """
        model = PostureDataOs()
        if include_optional:
            return PostureDataOs(
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                posture_check_id = '',
                timed_out = True,
                build = '',
                type = '',
                version = ''
            )
        else:
            return PostureDataOs(
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                posture_check_id = '',
                timed_out = True,
                build = '',
                type = '',
                version = '',
        )
        """

    def testPostureDataOs(self):
        """Test PostureDataOs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
