# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.api.mfa_api import MFAApi


class TestMFAApi(unittest.TestCase):
    """MFAApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MFAApi()

    def tearDown(self) -> None:
        pass

    def test_authenticate_mfa(self) -> None:
        """Test case for authenticate_mfa

        Complete MFA authentication
        """
        pass

    def test_create_mfa_recovery_codes(self) -> None:
        """Test case for create_mfa_recovery_codes

        For a completed MFA enrollment regenerate the recovery codes
        """
        pass

    def test_create_totp_token(self) -> None:
        """Test case for create_totp_token

        Create an MFA TOTP token that proves TOTP code checking has passed as a specific time for posture checks.
        """
        pass

    def test_delete_mfa(self) -> None:
        """Test case for delete_mfa

        Disable MFA for the current identity
        """
        pass

    def test_detail_mfa(self) -> None:
        """Test case for detail_mfa

        Returns the current status of MFA enrollment
        """
        pass

    def test_detail_mfa_qr_code(self) -> None:
        """Test case for detail_mfa_qr_code

        Show a QR code for unverified MFA enrollments
        """
        pass

    def test_detail_mfa_recovery_codes(self) -> None:
        """Test case for detail_mfa_recovery_codes

        For a completed MFA enrollment view the current recovery codes
        """
        pass

    def test_enroll_mfa(self) -> None:
        """Test case for enroll_mfa

        Initiate MFA enrollment
        """
        pass

    def test_remove_identity_mfa(self) -> None:
        """Test case for remove_identity_mfa

        Remove MFA from an identitity
        """
        pass

    def test_verify_mfa(self) -> None:
        """Test case for verify_mfa

        Complete MFA enrollment by verifying a time based one time token
        """
        pass


if __name__ == '__main__':
    unittest.main()
