# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.policy_advice import PolicyAdvice

class TestPolicyAdvice(unittest.TestCase):
    """PolicyAdvice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyAdvice:
        """Test PolicyAdvice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyAdvice`
        """
        model = PolicyAdvice()
        if include_optional:
            return PolicyAdvice(
                common_routers = [
                    null
                    ],
                identity = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                identity_id = '',
                identity_router_count = 1.337,
                is_bind_allowed = True,
                is_dial_allowed = True,
                service = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                service_id = '',
                service_router_count = 1.337
            )
        else:
            return PolicyAdvice(
        )
        """

    def testPolicyAdvice(self):
        """Test PolicyAdvice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
