# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.auth_policy_secondary import AuthPolicySecondary

class TestAuthPolicySecondary(unittest.TestCase):
    """AuthPolicySecondary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthPolicySecondary:
        """Test AuthPolicySecondary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthPolicySecondary`
        """
        model = AuthPolicySecondary()
        if include_optional:
            return AuthPolicySecondary(
                require_ext_jwt_signer = '',
                require_totp = True
            )
        else:
            return AuthPolicySecondary(
                require_totp = True,
        )
        """

    def testAuthPolicySecondary(self):
        """Test AuthPolicySecondary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
