# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.auth_policy_create import AuthPolicyCreate

class TestAuthPolicyCreate(unittest.TestCase):
    """AuthPolicyCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthPolicyCreate:
        """Test AuthPolicyCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthPolicyCreate`
        """
        model = AuthPolicyCreate()
        if include_optional:
            return AuthPolicyCreate(
                name = '',
                primary = openziti_edge_management.models.auth_policy_primary.authPolicyPrimary(
                    cert = openziti_edge_management.models.auth_policy_primary_cert.authPolicyPrimaryCert(
                        allow_expired_certs = True, 
                        allowed = True, ), 
                    ext_jwt = openziti_edge_management.models.auth_policy_primary_ext_jwt.authPolicyPrimaryExtJwt(
                        allowed = True, 
                        allowed_signers = [
                            ''
                            ], ), 
                    updb = openziti_edge_management.models.auth_policy_primary_updb.authPolicyPrimaryUpdb(
                        allowed = True, 
                        lockout_duration_minutes = 56, 
                        max_attempts = 56, 
                        min_password_length = 56, 
                        require_mixed_case = True, 
                        require_number_char = True, 
                        require_special_char = True, ), ),
                secondary = openziti_edge_management.models.auth_policy_secondary.authPolicySecondary(
                    require_ext_jwt_signer = '', 
                    require_totp = True, ),
                tags = None
            )
        else:
            return AuthPolicyCreate(
                name = '',
                primary = openziti_edge_management.models.auth_policy_primary.authPolicyPrimary(
                    cert = openziti_edge_management.models.auth_policy_primary_cert.authPolicyPrimaryCert(
                        allow_expired_certs = True, 
                        allowed = True, ), 
                    ext_jwt = openziti_edge_management.models.auth_policy_primary_ext_jwt.authPolicyPrimaryExtJwt(
                        allowed = True, 
                        allowed_signers = [
                            ''
                            ], ), 
                    updb = openziti_edge_management.models.auth_policy_primary_updb.authPolicyPrimaryUpdb(
                        allowed = True, 
                        lockout_duration_minutes = 56, 
                        max_attempts = 56, 
                        min_password_length = 56, 
                        require_mixed_case = True, 
                        require_number_char = True, 
                        require_special_char = True, ), ),
                secondary = openziti_edge_management.models.auth_policy_secondary.authPolicySecondary(
                    require_ext_jwt_signer = '', 
                    require_totp = True, ),
        )
        """

    def testAuthPolicyCreate(self):
        """Test AuthPolicyCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
