# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.posture_check_mac_address_create import PostureCheckMacAddressCreate

class TestPostureCheckMacAddressCreate(unittest.TestCase):
    """PostureCheckMacAddressCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostureCheckMacAddressCreate:
        """Test PostureCheckMacAddressCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostureCheckMacAddressCreate`
        """
        model = PostureCheckMacAddressCreate()
        if include_optional:
            return PostureCheckMacAddressCreate(
                mac_addresses = [
                    ''
                    ]
            )
        else:
            return PostureCheckMacAddressCreate(
                mac_addresses = [
                    ''
                    ],
        )
        """

    def testPostureCheckMacAddressCreate(self):
        """Test PostureCheckMacAddressCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
