# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.api.edge_router_api import EdgeRouterApi


class TestEdgeRouterApi(unittest.TestCase):
    """EdgeRouterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EdgeRouterApi()

    def tearDown(self) -> None:
        pass

    def test_create_edge_router(self) -> None:
        """Test case for create_edge_router

        Create an edge router
        """
        pass

    def test_delete_edge_router(self) -> None:
        """Test case for delete_edge_router

        Delete an edge router
        """
        pass

    def test_detail_edge_router(self) -> None:
        """Test case for detail_edge_router

        Retrieves a single edge router
        """
        pass

    def test_list_edge_router_edge_router_policies(self) -> None:
        """Test case for list_edge_router_edge_router_policies

        List the edge router policies that affect an edge router
        """
        pass

    def test_list_edge_router_identities(self) -> None:
        """Test case for list_edge_router_identities

        List associated identities
        """
        pass

    def test_list_edge_router_service_edge_router_policies(self) -> None:
        """Test case for list_edge_router_service_edge_router_policies

        List the service policies that affect an edge router
        """
        pass

    def test_list_edge_router_services(self) -> None:
        """Test case for list_edge_router_services

        List associated services
        """
        pass

    def test_list_edge_routers(self) -> None:
        """Test case for list_edge_routers

        List edge routers
        """
        pass

    def test_patch_edge_router(self) -> None:
        """Test case for patch_edge_router

        Update the supplied fields on an edge router
        """
        pass

    def test_re_enroll_edge_router(self) -> None:
        """Test case for re_enroll_edge_router

        Re-enroll an edge router
        """
        pass

    def test_update_edge_router(self) -> None:
        """Test case for update_edge_router

        Update all fields on an edge router
        """
        pass


if __name__ == '__main__':
    unittest.main()
