# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.controller_detail import ControllerDetail

class TestControllerDetail(unittest.TestCase):
    """ControllerDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ControllerDetail:
        """Test ControllerDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ControllerDetail`
        """
        model = ControllerDetail()
        if include_optional:
            return ControllerDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                tags = None,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                api_addresses = {
                    'key' : [
                        openziti_edge_management.models.api_address.apiAddress(
                            url = '', 
                            version = '', )
                        ]
                    },
                cert_pem = '',
                ctrl_address = '',
                fingerprint = '',
                is_online = True,
                last_joined_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = ''
            )
        else:
            return ControllerDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cert_pem = '',
                fingerprint = '',
                is_online = True,
                last_joined_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
        )
        """

    def testControllerDetail(self):
        """Test ControllerDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
