# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.ca_detail import CaDetail

class TestCaDetail(unittest.TestCase):
    """CaDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaDetail:
        """Test CaDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaDetail`
        """
        model = CaDetail()
        if include_optional:
            return CaDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                tags = None,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cert_pem = '',
                external_id_claim = openziti_edge_management.models.external_id_claim.externalIdClaim(
                    index = 56, 
                    location = 'COMMON_NAME', 
                    matcher = 'ALL', 
                    matcher_criteria = '', 
                    parser = 'NONE', 
                    parser_criteria = '', ),
                fingerprint = '',
                identity_name_format = '',
                identity_roles = [
                    ''
                    ],
                is_auth_enabled = True,
                is_auto_ca_enrollment_enabled = True,
                is_ott_ca_enrollment_enabled = True,
                is_verified = False,
                name = '',
                verification_token = ''
            )
        else:
            return CaDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cert_pem = '',
                fingerprint = '',
                identity_name_format = '',
                identity_roles = [
                    ''
                    ],
                is_auth_enabled = True,
                is_auto_ca_enrollment_enabled = True,
                is_ott_ca_enrollment_enabled = True,
                is_verified = False,
                name = '',
        )
        """

    def testCaDetail(self):
        """Test CaDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
