# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.api_session_detail import ApiSessionDetail

class TestApiSessionDetail(unittest.TestCase):
    """ApiSessionDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiSessionDetail:
        """Test ApiSessionDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiSessionDetail`
        """
        model = ApiSessionDetail()
        if include_optional:
            return ApiSessionDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                tags = None,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                auth_queries = [
                    openziti_edge_management.models.auth_query_detail.authQueryDetail(
                        client_id = '', 
                        format = 'numeric', 
                        http_method = '', 
                        http_url = '', 
                        id = '', 
                        is_totp_enrolled = True, 
                        max_length = 56, 
                        min_length = 56, 
                        provider = 'ziti', 
                        scopes = [
                            ''
                            ], 
                        type_id = 'MFA', )
                    ],
                authenticator_id = '',
                cached_last_activity_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                config_types = [
                    ''
                    ],
                identity = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                identity_id = '',
                improper_client_cert_chain = True,
                ip_address = '',
                is_cert_extend_requested = True,
                is_cert_extendable = True,
                is_cert_key_roll_requested = True,
                is_mfa_complete = True,
                is_mfa_required = True,
                last_activity_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                token = ''
            )
        else:
            return ApiSessionDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                auth_queries = [
                    openziti_edge_management.models.auth_query_detail.authQueryDetail(
                        client_id = '', 
                        format = 'numeric', 
                        http_method = '', 
                        http_url = '', 
                        id = '', 
                        is_totp_enrolled = True, 
                        max_length = 56, 
                        min_length = 56, 
                        provider = 'ziti', 
                        scopes = [
                            ''
                            ], 
                        type_id = 'MFA', )
                    ],
                authenticator_id = '',
                config_types = [
                    ''
                    ],
                identity = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                identity_id = '',
                ip_address = '',
                is_cert_extendable = True,
                is_mfa_complete = True,
                is_mfa_required = True,
                token = '',
        )
        """

    def testApiSessionDetail(self):
        """Test ApiSessionDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
