# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.external_jwt_signer_patch import ExternalJwtSignerPatch

class TestExternalJwtSignerPatch(unittest.TestCase):
    """ExternalJwtSignerPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalJwtSignerPatch:
        """Test ExternalJwtSignerPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalJwtSignerPatch`
        """
        model = ExternalJwtSignerPatch()
        if include_optional:
            return ExternalJwtSignerPatch(
                audience = '',
                cert_pem = '',
                claims_property = '',
                client_id = '',
                enabled = True,
                enroll_attribute_claims_selector = '',
                enroll_auth_policy_id = '',
                enroll_name_claims_selector = '',
                enroll_to_cert_enabled = True,
                enroll_to_token_enabled = True,
                external_auth_url = '',
                issuer = '',
                jwks_endpoint = '',
                kid = '',
                name = 'MyApps Signer',
                scopes = [
                    ''
                    ],
                tags = None,
                target_token = 'ACCESS',
                use_external_id = True
            )
        else:
            return ExternalJwtSignerPatch(
        )
        """

    def testExternalJwtSignerPatch(self):
        """Test ExternalJwtSignerPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
