# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.controller_setting_effective import ControllerSettingEffective

class TestControllerSettingEffective(unittest.TestCase):
    """ControllerSettingEffective unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ControllerSettingEffective:
        """Test ControllerSettingEffective
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ControllerSettingEffective`
        """
        model = ControllerSettingEffective()
        if include_optional:
            return ControllerSettingEffective(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                tags = None,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                effective = openziti_edge_management.models.controller_settings.controllerSettings(
                    oidc = openziti_edge_management.models.controller_settings_oidc.controllerSettings_oidc(
                        post_logout_uris = [
                            ''
                            ], 
                        redirect_uris = [
                            ''
                            ], ), ),
                instance = openziti_edge_management.models.controller_settings.controllerSettings(
                    oidc = openziti_edge_management.models.controller_settings_oidc.controllerSettings_oidc(
                        post_logout_uris = [
                            ''
                            ], 
                        redirect_uris = [
                            ''
                            ], ), )
            )
        else:
            return ControllerSettingEffective(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testControllerSettingEffective(self):
        """Test ControllerSettingEffective"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
