# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.identity_detail import IdentityDetail

class TestIdentityDetail(unittest.TestCase):
    """IdentityDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityDetail:
        """Test IdentityDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityDetail`
        """
        model = IdentityDetail()
        if include_optional:
            return IdentityDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                tags = None,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                app_data = None,
                auth_policy = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                auth_policy_id = '',
                authenticators = openziti_edge_management.models.identity_authenticators.identityAuthenticators(
                    cert = openziti_edge_management.models.identity_authenticators_cert.identityAuthenticators_cert(
                        fingerprint = '', 
                        id = '', ), 
                    updb = openziti_edge_management.models.identity_authenticators_updb.identityAuthenticators_updb(
                        id = '', 
                        username = '', ), ),
                default_hosting_cost = 0,
                default_hosting_precedence = 'default',
                disabled = True,
                disabled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                disabled_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                edge_router_connection_status = 'online',
                enrollment = openziti_edge_management.models.identity_enrollments.identityEnrollments(
                    ott = openziti_edge_management.models.identity_enrollments_ott.identityEnrollments_ott(
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        jwt = '', 
                        token = '', ), 
                    ottca = openziti_edge_management.models.identity_enrollments_ottca.identityEnrollments_ottca(
                        ca = openziti_edge_management.models.entity_ref.entityRef(
                            _links = {
                                'key' : openziti_edge_management.models.link.link(
                                    comment = '', 
                                    href = '', 
                                    method = '', )
                                }, 
                            entity = '', 
                            id = '', 
                            name = '', ), 
                        ca_id = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        jwt = '', 
                        token = '', ), 
                    updb = openziti_edge_management.models.identity_enrollments_ott.identityEnrollments_ott(
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        jwt = '', 
                        token = '', ), ),
                env_info = openziti_edge_management.models.env_info.envInfo(
                    arch = '', 
                    domain = '', 
                    hostname = '', 
                    os = '', 
                    os_release = '', 
                    os_version = '', ),
                external_id = '',
                has_api_session = True,
                has_edge_router_connection = True,
                interfaces = [
                    openziti_edge_management.models.interface.interface(
                        addresses = [
                            ''
                            ], 
                        hardware_address = '', 
                        index = 0, 
                        is_broadcast = True, 
                        is_loopback = True, 
                        is_multicast = True, 
                        is_running = True, 
                        is_up = True, 
                        mtu = 0, 
                        name = '', )
                    ],
                is_admin = True,
                is_default_admin = True,
                is_mfa_enabled = True,
                name = '',
                permissions = [
                    'admin_readonly'
                    ],
                role_attributes = [
                    ''
                    ],
                sdk_info = openziti_edge_management.models.sdk_info.sdkInfo(
                    app_id = '', 
                    app_version = '', 
                    branch = '', 
                    revision = '', 
                    type = '', 
                    version = '', ),
                service_hosting_costs = {
                    'key' : 0
                    },
                service_hosting_precedences = {
                    'key' : 'default'
                    },
                type = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                type_id = ''
            )
        else:
            return IdentityDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                auth_policy = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                auth_policy_id = '',
                authenticators = openziti_edge_management.models.identity_authenticators.identityAuthenticators(
                    cert = openziti_edge_management.models.identity_authenticators_cert.identityAuthenticators_cert(
                        fingerprint = '', 
                        id = '', ), 
                    updb = openziti_edge_management.models.identity_authenticators_updb.identityAuthenticators_updb(
                        id = '', 
                        username = '', ), ),
                default_hosting_cost = 0,
                disabled = True,
                edge_router_connection_status = 'online',
                enrollment = openziti_edge_management.models.identity_enrollments.identityEnrollments(
                    ott = openziti_edge_management.models.identity_enrollments_ott.identityEnrollments_ott(
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        jwt = '', 
                        token = '', ), 
                    ottca = openziti_edge_management.models.identity_enrollments_ottca.identityEnrollments_ottca(
                        ca = openziti_edge_management.models.entity_ref.entityRef(
                            _links = {
                                'key' : openziti_edge_management.models.link.link(
                                    comment = '', 
                                    href = '', 
                                    method = '', )
                                }, 
                            entity = '', 
                            id = '', 
                            name = '', ), 
                        ca_id = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        jwt = '', 
                        token = '', ), 
                    updb = openziti_edge_management.models.identity_enrollments_ott.identityEnrollments_ott(
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        jwt = '', 
                        token = '', ), ),
                env_info = openziti_edge_management.models.env_info.envInfo(
                    arch = '', 
                    domain = '', 
                    hostname = '', 
                    os = '', 
                    os_release = '', 
                    os_version = '', ),
                external_id = '',
                has_api_session = True,
                has_edge_router_connection = True,
                is_admin = True,
                is_default_admin = True,
                is_mfa_enabled = True,
                name = '',
                permissions = [
                    'admin_readonly'
                    ],
                role_attributes = [
                    ''
                    ],
                sdk_info = openziti_edge_management.models.sdk_info.sdkInfo(
                    app_id = '', 
                    app_version = '', 
                    branch = '', 
                    revision = '', 
                    type = '', 
                    version = '', ),
                service_hosting_costs = {
                    'key' : 0
                    },
                service_hosting_precedences = {
                    'key' : 'default'
                    },
                type = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                type_id = '',
        )
        """

    def testIdentityDetail(self):
        """Test IdentityDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
