# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.terminator_create import TerminatorCreate

class TestTerminatorCreate(unittest.TestCase):
    """TerminatorCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerminatorCreate:
        """Test TerminatorCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerminatorCreate`
        """
        model = TerminatorCreate()
        if include_optional:
            return TerminatorCreate(
                address = '',
                binding = '',
                cost = 0,
                identity = '',
                identity_secret = 'YQ==',
                precedence = 'default',
                router = '',
                service = '',
                tags = None
            )
        else:
            return TerminatorCreate(
                address = '',
                binding = '',
                router = '',
                service = '',
        )
        """

    def testTerminatorCreate(self):
        """Test TerminatorCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
