# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.posture_check_failure_operating_system import PostureCheckFailureOperatingSystem

class TestPostureCheckFailureOperatingSystem(unittest.TestCase):
    """PostureCheckFailureOperatingSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostureCheckFailureOperatingSystem:
        """Test PostureCheckFailureOperatingSystem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostureCheckFailureOperatingSystem`
        """
        model = PostureCheckFailureOperatingSystem()
        if include_optional:
            return PostureCheckFailureOperatingSystem(
                actual_value = openziti_edge_management.models.posture_check_failure_operating_system_actual.postureCheckFailureOperatingSystemActual(
                    type = '', 
                    version = '', ),
                expected_value = [
                    openziti_edge_management.models.operating_system.operatingSystem(
                        type = 'Windows', 
                        versions = [
                            ''
                            ], )
                    ]
            )
        else:
            return PostureCheckFailureOperatingSystem(
                actual_value = openziti_edge_management.models.posture_check_failure_operating_system_actual.postureCheckFailureOperatingSystemActual(
                    type = '', 
                    version = '', ),
                expected_value = [
                    openziti_edge_management.models.operating_system.operatingSystem(
                        type = 'Windows', 
                        versions = [
                            ''
                            ], )
                    ],
        )
        """

    def testPostureCheckFailureOperatingSystem(self):
        """Test PostureCheckFailureOperatingSystem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
