# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.controller_setting_update import ControllerSettingUpdate

class TestControllerSettingUpdate(unittest.TestCase):
    """ControllerSettingUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ControllerSettingUpdate:
        """Test ControllerSettingUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ControllerSettingUpdate`
        """
        model = ControllerSettingUpdate()
        if include_optional:
            return ControllerSettingUpdate(
                oidc = openziti_edge_management.models.controller_settings_oidc.controllerSettings_oidc(
                    post_logout_uris = [
                        ''
                        ], 
                    redirect_uris = [
                        ''
                        ], ),
                tags = None
            )
        else:
            return ControllerSettingUpdate(
        )
        """

    def testControllerSettingUpdate(self):
        """Test ControllerSettingUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
