# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.list_identity_types_envelope import ListIdentityTypesEnvelope

class TestListIdentityTypesEnvelope(unittest.TestCase):
    """ListIdentityTypesEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListIdentityTypesEnvelope:
        """Test ListIdentityTypesEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListIdentityTypesEnvelope`
        """
        model = ListIdentityTypesEnvelope()
        if include_optional:
            return ListIdentityTypesEnvelope(
                data = [
                    null
                    ],
                meta = openziti_edge_management.models.meta.meta(
                    api_enrollment_version = '', 
                    api_version = '', 
                    filterable_fields = [
                        ''
                        ], 
                    pagination = openziti_edge_management.models.pagination.pagination(
                        limit = 1.337, 
                        offset = 1.337, 
                        total_count = 1.337, ), )
            )
        else:
            return ListIdentityTypesEnvelope(
                data = [
                    null
                    ],
                meta = openziti_edge_management.models.meta.meta(
                    api_enrollment_version = '', 
                    api_version = '', 
                    filterable_fields = [
                        ''
                        ], 
                    pagination = openziti_edge_management.models.pagination.pagination(
                        limit = 1.337, 
                        offset = 1.337, 
                        total_count = 1.337, ), ),
        )
        """

    def testListIdentityTypesEnvelope(self):
        """Test ListIdentityTypesEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
