# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.posture_check_operating_system_update import PostureCheckOperatingSystemUpdate

class TestPostureCheckOperatingSystemUpdate(unittest.TestCase):
    """PostureCheckOperatingSystemUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostureCheckOperatingSystemUpdate:
        """Test PostureCheckOperatingSystemUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostureCheckOperatingSystemUpdate`
        """
        model = PostureCheckOperatingSystemUpdate()
        if include_optional:
            return PostureCheckOperatingSystemUpdate(
                operating_systems = [
                    openziti_edge_management.models.operating_system.operatingSystem(
                        type = 'Windows', 
                        versions = [
                            ''
                            ], )
                    ]
            )
        else:
            return PostureCheckOperatingSystemUpdate(
                operating_systems = [
                    openziti_edge_management.models.operating_system.operatingSystem(
                        type = 'Windows', 
                        versions = [
                            ''
                            ], )
                    ],
        )
        """

    def testPostureCheckOperatingSystemUpdate(self):
        """Test PostureCheckOperatingSystemUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
