# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.api_error import ApiError

class TestApiError(unittest.TestCase):
    """ApiError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiError:
        """Test ApiError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiError`
        """
        model = ApiError()
        if include_optional:
            return ApiError(
                args = openziti_edge_management.models.api_error_args.apiErrorArgs(
                    url_vars = {
                        'key' : ''
                        }, ),
                cause = None,
                cause_message = '',
                code = '',
                data = { },
                message = '',
                request_id = ''
            )
        else:
            return ApiError(
        )
        """

    def testApiError(self):
        """Test ApiError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
