# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.enrollment_detail import EnrollmentDetail

class TestEnrollmentDetail(unittest.TestCase):
    """EnrollmentDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnrollmentDetail:
        """Test EnrollmentDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnrollmentDetail`
        """
        model = EnrollmentDetail()
        if include_optional:
            return EnrollmentDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                tags = None,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ca_id = '',
                edge_router = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                edge_router_id = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                identity = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                identity_id = '',
                jwt = '',
                method = '',
                token = '',
                transit_router = openziti_edge_management.models.entity_ref.entityRef(
                    _links = {
                        'key' : openziti_edge_management.models.link.link(
                            comment = '', 
                            href = '', 
                            method = '', )
                        }, 
                    entity = '', 
                    id = '', 
                    name = '', ),
                transit_router_id = '',
                username = ''
            )
        else:
            return EnrollmentDetail(
                links = {
                    'key' : openziti_edge_management.models.link.link(
                        comment = '', 
                        href = '', 
                        method = '', )
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                method = '',
                token = '',
        )
        """

    def testEnrollmentDetail(self):
        """Test EnrollmentDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
