# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.api.enroll_api import EnrollApi


class TestEnrollApi(unittest.TestCase):
    """EnrollApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnrollApi()

    def tearDown(self) -> None:
        pass

    def test_extend_current_identity_authenticator(self) -> None:
        """Test case for extend_current_identity_authenticator

        Allows the current identity to recieve a new certificate associated with a certificate based authenticator
        """
        pass

    def test_extend_verify_current_identity_authenticator(self) -> None:
        """Test case for extend_verify_current_identity_authenticator

        Allows the current identity to validate reciept of a new client certificate
        """
        pass


if __name__ == '__main__':
    unittest.main()
