# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.auth_policy_primary_updb_patch import AuthPolicyPrimaryUpdbPatch

class TestAuthPolicyPrimaryUpdbPatch(unittest.TestCase):
    """AuthPolicyPrimaryUpdbPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthPolicyPrimaryUpdbPatch:
        """Test AuthPolicyPrimaryUpdbPatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthPolicyPrimaryUpdbPatch`
        """
        model = AuthPolicyPrimaryUpdbPatch()
        if include_optional:
            return AuthPolicyPrimaryUpdbPatch(
                allowed = True,
                lockout_duration_minutes = 56,
                max_attempts = 56,
                min_password_length = 56,
                require_mixed_case = True,
                require_number_char = True,
                require_special_char = True
            )
        else:
            return AuthPolicyPrimaryUpdbPatch(
        )
        """

    def testAuthPolicyPrimaryUpdbPatch(self):
        """Test AuthPolicyPrimaryUpdbPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
