# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.identity_type import IdentityType

class TestIdentityType(unittest.TestCase):
    """IdentityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityType(self):
        """Test IdentityType"""
        # inst = IdentityType()

if __name__ == '__main__':
    unittest.main()
