# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.posture_checks_failure_mfa_criteria import PostureChecksFailureMfaCriteria

class TestPostureChecksFailureMfaCriteria(unittest.TestCase):
    """PostureChecksFailureMfaCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostureChecksFailureMfaCriteria:
        """Test PostureChecksFailureMfaCriteria
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostureChecksFailureMfaCriteria`
        """
        model = PostureChecksFailureMfaCriteria()
        if include_optional:
            return PostureChecksFailureMfaCriteria(
                passed_mfa_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                timeout_remaining_seconds = 56,
                timeout_seconds = 56,
                unlocked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                woken_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PostureChecksFailureMfaCriteria(
                passed_mfa_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                timeout_remaining_seconds = 56,
                timeout_seconds = 56,
                unlocked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                woken_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPostureChecksFailureMfaCriteria(self):
        """Test PostureChecksFailureMfaCriteria"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
