# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.26.53
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openziti_edge_management.models.posture_check_failure_mfa import PostureCheckFailureMfa

class TestPostureCheckFailureMfa(unittest.TestCase):
    """PostureCheckFailureMfa unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostureCheckFailureMfa:
        """Test PostureCheckFailureMfa
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostureCheckFailureMfa`
        """
        model = PostureCheckFailureMfa()
        if include_optional:
            return PostureCheckFailureMfa(
                actual_value = openziti_edge_management.models.posture_checks_failure_mfa_values.postureChecksFailureMfaValues(
                    passed_mfa = True, 
                    passed_on_unlock = True, 
                    passed_on_wake = True, 
                    timed_out = True, ),
                criteria = openziti_edge_management.models.posture_checks_failure_mfa_criteria.postureChecksFailureMfaCriteria(
                    passed_mfa_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    timeout_remaining_seconds = 56, 
                    timeout_seconds = 56, 
                    unlocked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    woken_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                expected_value = openziti_edge_management.models.posture_checks_failure_mfa_values.postureChecksFailureMfaValues(
                    passed_mfa = True, 
                    passed_on_unlock = True, 
                    passed_on_wake = True, 
                    timed_out = True, )
            )
        else:
            return PostureCheckFailureMfa(
                actual_value = openziti_edge_management.models.posture_checks_failure_mfa_values.postureChecksFailureMfaValues(
                    passed_mfa = True, 
                    passed_on_unlock = True, 
                    passed_on_wake = True, 
                    timed_out = True, ),
                criteria = openziti_edge_management.models.posture_checks_failure_mfa_criteria.postureChecksFailureMfaCriteria(
                    passed_mfa_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    timeout_remaining_seconds = 56, 
                    timeout_seconds = 56, 
                    unlocked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    woken_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                expected_value = openziti_edge_management.models.posture_checks_failure_mfa_values.postureChecksFailureMfaValues(
                    passed_mfa = True, 
                    passed_on_unlock = True, 
                    passed_on_wake = True, 
                    timed_out = True, ),
        )
        """

    def testPostureCheckFailureMfa(self):
        """Test PostureCheckFailureMfa"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
